# Generated by Django 4.1.7 on 2023-06-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='departmentdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.CharField(blank=True, max_length=100, null=True)),
                ('Describe', models.CharField(blank=True, max_length=100, null=True)),
                ('Image', models.ImageField(upload_to='Profile')),
            ],
        ),
    ]
