# Generated by Django 4.1.7 on 2023-06-13 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_doctorsdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorsdb',
            old_name='Doctorname',
            new_name='Department',
        ),
        migrations.RenameField(
            model_name='doctorsdb',
            old_name='Position',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='doctorsdb',
            old_name='Image',
            new_name='image',
        ),
    ]
