# Generated by Django 4.1.7 on 2023-06-17 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_doctorname_doctorsdb_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorsdb',
            old_name='Department',
            new_name='Departmentname',
        ),
    ]
