# Generated by Django 4.1.7 on 2023-06-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_department_doctorsdb_departmentname'),
    ]

    operations = [
        migrations.CreateModel(
            name='servicedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service', models.CharField(blank=True, max_length=100, null=True)),
                ('Describe', models.CharField(blank=True, max_length=100, null=True)),
                ('Image', models.ImageField(upload_to='ServiceProfile')),
            ],
        ),
    ]
