# Generated by Django 4.1.7 on 2023-06-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinmentdb',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
