# Generated by Django 4.1.7 on 2023-06-20 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_userlogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoinmentdb',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
