# Generated by Django 4.1.7 on 2023-07-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_messagedb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinmentdb',
            name='time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
